name: Deploy Pull Request to Ephemeral Environment
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete PR environment on Railway
        uses: Faolain/railway-pr-delete@v1.0.11
        with:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          DEST_ENV_NAME: pr-${{ github.event.pull_request.number }}

      - name: Delete a Neon Branch 🚀
        uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch: pr-${{ github.event.pull_request.number }}
          api_key: ${{ secrets.NEON_API_KEY }}
