name: Deploy Preview

on: [pull_request]

jobs:
  deploy-preview:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name: Install Bun CLI
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Create a Neon branch
        uses: neondatabase/create-branch-action@v4
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_name: ${{ steps.branch-name.outputs.current_branch }}
          api_key: ${{ secrets.NEON_API_KEY }}
          username: ${{ secrets.NEON_USERNAME }}
        id: create-branch

      - run: echo project_id ${{ steps.create-branch.outputs.project_id }}
      - run: echo branch_id ${{ steps.create-branch.outputs.branch_id }}

      - name: Run Drizzle Migrate
        run: |
          touch .env
          echo "DATABASE_URL=${{ steps.create-branch.outputs.db_url }}" >> .env
          echo "DIRECT_URL=${{ steps.create-branch.outputs.db_url }}" >> .env
          bun run migrate

      - name: Install Vercel CLI
        run: npm install --g vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Preview to Vercel
        id: deploy
        run: echo preview_url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}) >> $GITHUB_OUTPUT

      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Vercel Preview URL :rocket: : ${{ steps.deploy.outputs.preview_url }}
            Neon branch :elephant: : https://console.neon.tech/app/projects/${{ secrets.NEON_PROJECT_ID }}/branches/${{ steps.get-neon-branch-id.outputs.branch_id }}
