name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name: Install the Neon CLI
        run: npm install -g neonctl

      - name: get Neon branch ID
        id: get-neon-branch-id
        run: |
          echo ${{ steps.branch-name.outputs.head_ref_branch }} >> $GITHUB_OUTPUT
          echo branch_id=$(neonctl branches get ${{ steps.branch-name.outputs.head_ref_branch }} --project-id ${{ secrets.NEON_PROJECT_ID }} --api-key ${{ secrets.NEON_API_KEY }} --output json | jq -r '.id') >> $GITHUB_OUTPUT

      - name: Install Bun CLI
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Packages
        run: bun install

      - name: Run Drizzle Migrate
        run: |
          touch .env
          echo DATABASE_URL=$(neonctl cs ${{ secrets.NEON_MAIN_BRANCH_NAME }} --project-id ${{ secrets.NEON_PROJECT_ID }} --role-name ${{ secrets.PG_USERNAME }} --database-name ${{ secrets.PG_DATABASE }} --api-key ${{ secrets.NEON_API_KEY }}) >> .env
          bun run migrate
